### ISSUE TITLE
amb server, error

### ISSUE THREAD

**Issue by yangjiandong** [animajs/amb#13]
```
$ amb server
util.js:634
  ctor.prototype = Object.create(superCtor.prototype, {
                                          ^
TypeError: Cannot read property 'prototype' of undefined
  at Object.exports.inherits (util.js:634:43)
  at Object.<anonymous> (/usr/local/lib/node_modules/amb/node_modules/spm-server/node_modules/http-proxy/lib/http-proxy/index.js:108:17)
  at Module._compile (module.js:460:26)
  at Object.Module._extensions..js (module.js:478:10)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (module.js:384:17)
  at Object.<anonymous> (/usr/local/lib/node_modules/amb/node_modules/spm-server/node_modules/http-proxy/lib/http-proxy.js:4:17)
  at Module._compile (module.js:460:26)
  at Object.Module._extensions..js (module.js:478:10)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (module.js:384:17)
  at Object.<anonymous> (/usr/local/lib/node_modules/amb/node_modules/spm-server/node_modules/http-proxy/index.js:13:18)
  at Module._compile (module.js:460:26)
  at Object.Module._extensions..js (module.js:478:10)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (module.js:384:17)
  at Object.<anonymous> (/usr/local/lib/node_modules/amb/node_modules/spm-server/index.js:10:17)
  at Module._compile (module.js:460:26)
  at Object.Module._extensions..js (module.js:478:10)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (module.js:384:17)
  at Object.<anonymous> (/usr/local/lib/node_modules/amb/bin/amb-server:42:1)
  at Module._compile (module.js:460:26)
  at Object.Module._extensions..js (module.js:478:10)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Function.Module.runMain (module.js:501:10)
  at startup (node.js:129:16)
  at node.js:814:3
```

mac
node - v0.12.2
npm - 2.7.5
spm - 3.6.0
amb - 2.1.3

**Comment by yincongyang** [comment]
我在windows下面也出现了同样的问题，同问。。。
